version: "3.7"
services:
  socialnetwork-postgres:
    image: postgres
    container_name: "socialnetwork-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=socialnetwork
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
