version: "3.7"
services:
  postgres:
    image: postgres
    container_name: "socialnetwork-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=socialnetwork
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build:
      context: server
    container_name: "socialnetwork-api"
    environment:
      - SN_DATABASE_NAME=socialnetwork
      - SN_DATABASE_HOST=socialnetwork-database
      - SN_DATABASE_PORT=5432
      - SN_DATABASE_USERNAME=postgres
      - SN_DATABASE_PASSWORD=password
      - SN_API_PORT=9000
    links:
      - postgres:socialnetwork-database
  webapp:
    build:
      context: webapp
    container_name: "socialnetwork-app"
    environment:
      - SN_API_HOST=socialnetwork-api
      - SN_API_PORT=9000
    links:
      - api:socialnetwork-api
    ports:
      - 80:80
      - 443:443
volumes:
  pgdata:
