
spring:
  datasource:
    url: jdbc:postgresql://${SN_DATABASE_HOST:localhost}:${SN_DATABASE_PORT:5432}/socialnetwork
    username: ${SN_DATABASE_USERNAME:postgres}
    password: ${SN_DATABASE_PASSWORD:password}
  liquibase:
    liquibase-schema: public
    change-log: classpath:database/liquibase-changelog.xml
    default-schema: socialnetwork
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: ${SN_API_PORT:9000}
