###
POST http://localhost:9000/api/account/register
Content-Type: application/json

{
  "mail": "user@domain.com",
  "password": "123456",
  "firstname": "some",
  "lastname": "one"
}

###
POST http://localhost:9000/api/account/login
Content-Type: application/json

{
  "mail": "user@domain.com",
  "password": "123456"
}

> login.js

###
POST http://localhost:9000/api/messages
Content-Type: application/json
Authorization: {{token}}

{
  "content": "TEST",
  "type": "PROFILE"
}

> 200.js

###

